# Generated by Django 4.2 on 2025-02-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='founditem',
            table='Found_item',
        ),
    ]
