# Generated by Django 4.1.13 on 2025-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("found_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
