# Generated by Django 4.2 on 2025-02-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found_app', '0002_alter_founditem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='date_lost',
            new_name='date_found',
        ),
    ]
