# Generated by Django 4.2 on 2025-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
